### ISSUE TITLE
Benefits over s3fs?

### ISSUE THREAD

**Issue by jeremy-ellis-tech** [matrix-org/synapse-s3-storage-provider#40]
I was wondering what the benefits of using this would be over something like [s3fs](https://github.com/s3fs-fuse/s3fs-fuse). ie. Couldn't you mount an s3 bucket as a file system with s3fs, matrix could access it with the file_system module and you would get the same effect?

**Comment by clokep** [comment]
@jeremy-ellis-tech I suspect the obvious benefit is that this is cross-platform. 😄 

I'm not really familiar with s3fs, but your suggested setup sounds like it would work. Looking through the readme for s3fs, I'd be a bit concerned about using that in a situation where there are multiple workers backed by the same media store. It might work OK though. (I've also generally found error handling when using a setup like that to be a bit more frustrating since it will act like a file system...until it breaks and then give nonsensical errors back to code that expects a standard file system.)

If you end up trying it, would be interesting to report back how it works!

You might also want to ask in #synapse:matrix.org to see if people have tried similar things to this. I'm going to close this though since there isn't really an action to come out of it!

**Comment by jeremy-ellis-tech** [comment]
Thanks for the response. I'll ask around and give it a go to see if I hit any issues.
