### ISSUE TITLE
It saves the media in both local and the S3 bucket

### ISSUE THREAD

**Issue by Ibrahim-AbouElseoud** [matrix-org/synapse-s3-storage-provider#58]
I had successfully setup the module and the homeserver config file, as it uploads the media to the bucket successfully ; however, after inspecting the local media directory it seems to store the media in there as well, which is very counter productive concerning using an S3 bucket in the first place.

So my question is, should I modify the homeserver.yaml file to remove or modify the media_store_path and uploads_path ?

Since I would like it to only upload and serve media from the S3 bucket.

Or should I be constantly running the clean up script mentioned in the readme on a schedule ?

Or is this a bug?

**Comment by erikjohnston** [comment]
Currently you need to run the clean up script on a schedule to clean up older data, that way each server can decide the cost/benefit of keeping everything locally vs only keeping very recent uploads locally.

Ideally we'd do it as part of the module (or Synapse) so that you didn't have to run a separate job to do it, but we don't have that today.
